import type { Metadata } from "next"
import "./globals.css";
import Navbar from "@/components/common/Navbar";
import ThemeProvider from "@/components/common/ThemeProvider"
import Footer from "@/components/common/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en" suppressHydrationWarning
    >
      <body className = {`font-hanken-grotesk antialiased`}>
        <ThemeProvider attribute="class" defaultTheme = "system" enableSystem>
        <Navbar></Navbar>
        {children}
        <Footer></Footer>
       </ThemeProvider>
      </body>
    </html>
  );
}
